stages:
  - make_release

make_release:
  stage: make_release
  image: alpine:latest
  script: |
    apk update
    apk add haxe
    yes | haxelib install all
    haxe build.hxml
    echo "Releasing $CI_COMMIT_TAG"
  artifacts:
    paths:
      - out
